'use client';
import { useState } from 'react';
import { Home, Files, History, Settings2, SquarePen, Search, PanelLeftClose, PanelLeftOpen, ChevronRight, Plus, X } from 'lucide-react';
import { DotAvatar } from './DotIdentity';
import type { DotProfile } from '../lib/dot-profile';
import ComputerThumbnail from './ComputerThumbnail';
import type { Dot, Conversation } from '../lib/api';

export function DotRail({ sidebarOpen, onSidebar, onHome, onFiles, onActivity, onSettings }: { sidebarOpen: boolean; onSidebar: () => void; onHome: () => void; onFiles: () => void; onActivity: () => void; onSettings: () => void }) {
  return <nav className="dot-rail" aria-label="주 메뉴"><button aria-label="내 dot" title="내 dot" onClick={onHome} className="rail-home"><Home size={21} fill="currentColor" /></button><button aria-label="탐색 메뉴" title="탐색 메뉴" aria-expanded={sidebarOpen} onClick={onSidebar}>{sidebarOpen ? <PanelLeftClose size={20} /> : <PanelLeftOpen size={20} />}</button><button aria-label="결과물" title="결과물" onClick={onFiles}><Files size={20} /></button><button aria-label="작업 기록" title="작업 기록" onClick={onActivity}><History size={20} /></button><button className="rail-settings" aria-label="설정" title="설정" onClick={onSettings}><Settings2 size={20} /></button></nav>;
}
export default function DotSidebar({ profile, conversations, currentId, onSelect, onNew, onHome, onClose, dots, activeDotId, onDot, onAddDot }: { profile: DotProfile; conversations: Conversation[]; currentId?: string; onSelect: (id: string) => void; onNew: () => void; onHome: () => void; onClose: () => void; dots: Dot[]; activeDotId: string; onDot: (id: string) => void; onAddDot: () => void }) {
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState('');
  const rows = conversations.filter(c => c.title.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <aside className="dot-sidebar" aria-label="탐색"><header><strong>OhMyDots</strong><button className="icon-button" aria-label="대화 검색" aria-expanded={searchOpen} onClick={() => setSearchOpen(!searchOpen)}><Search size={19} /></button><button className="icon-button" aria-label="탐색 닫기" onClick={onClose}><PanelLeftClose size={19} /></button></header><button className="sidebar-action" onClick={onNew}><SquarePen size={20} />새 대화</button><button className="sidebar-action selected" onClick={onHome}><DotAvatar profile={profile} size={26} />내 dot</button>{searchOpen && <label className="sidebar-search"><Search size={15} /><input autoFocus aria-label="대화 검색어" placeholder="대화 검색" value={query} onChange={e => setQuery(e.target.value)} /><button className="icon-button" aria-label="검색 초기화" onClick={() => setQuery('')}><X size={14} /></button></label>}<div className="sidebar-section-title">최근 대화 <ChevronRight size={13} /></div><nav className="sidebar-conversations" aria-label="최근 대화">{rows.map(c => <button key={c.id} aria-current={currentId === c.id ? 'page' : undefined} onClick={() => onSelect(c.id)} title={c.title}>{c.title}</button>)}{!rows.length && <p>{query ? '일치하는 대화가 없어요.' : '첫 대화를 시작해 보세요.'}</p>}</nav><section className="sidebar-dots" aria-label="Dots"><div className="sidebar-dots-heading"><strong>Dots</strong><button className="icon-button" aria-label="Dot 추가" title="Dot 추가" onClick={onAddDot}><Plus size={18} /></button></div><nav aria-label="내 Dots">{dots.map(dot => <button key={dot.id} className={activeDotId === dot.id ? "selected" : ""} aria-current={activeDotId === dot.id ? "page" : undefined} onClick={() => onDot(dot.id)}><DotAvatar profile={dot} size={34} /><span>{dot.name}</span><ComputerThumbnail sessionId={dot.computer_id} name={dot.name} /></button>)}</nav><button className="sidebar-add-dot" onClick={onAddDot}><Plus size={17} />Dots 추가</button></section></aside>;
}
