'use client';
import { useEffect, useState } from 'react';
import { ArrowUp, ChevronDown, Download, File, FileText, FolderOpen, Grid2X2, Image as ImageIcon, Library, List, Loader2, PanelLeft, Search, SquarePen, X } from 'lucide-react';
import Markdown from 'react-markdown';
export type FilePreview = { path: string; text?: string; loading?: boolean; error?: string };
type Artifact = { path: string; size: number };
function kind(path: string) { return /\.(png|jpe?g|gif|webp)$/i.test(path) ? 'images' : /\.(md|txt|csv|json|pdf|docx|xlsx|pptx|html)$/i.test(path) ? 'documents' : 'other'; }
function fileUrl(path: string, download = false) { return '/api/artifact-download/' + path.split('/').map(encodeURIComponent).join('/') + '?download=' + download; }
function size(bytes: number) { return bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function FileIcon({ path }: { path: string }) { return kind(path) === 'images' ? <ImageIcon size={21} /> : <FileText size={21} />; }
export default function SpacesWorkspace({ files, preview, onFile, onClose, onBack, onCompose }: { files: Artifact[]; preview: FilePreview | null; onFile: (path: string) => void; onClose: () => void; onBack: () => void; onCompose: (prompt: string) => void }) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [grid, setGrid] = useState(false); const [zoom, setZoom] = useState('100'); const [question, setQuestion] = useState(''); const [sidebar, setSidebar] = useState(false);
  useEffect(() => { setQuestion(''); setZoom('100'); }, [preview?.path]);
  const matches = files.filter(file => file.path.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || kind(file.path) === filter));
  const selected = files.find(file => file.path === preview?.path);
  const ask = () => { if (preview && question.trim()) onCompose(`${preview.path} 파일에 대해: ${question.trim()}`); };
  return <section className={'spaces-app ' + (sidebar ? 'library-visible' : '')} aria-label="스페이스">
    <aside className="spaces-sidebar"><h2>스페이스</h2><button className="spaces-nav" onClick={() => onCompose('새 문서 초안을 만들어줘')}><SquarePen size={19} />새 페이지</button>
      <nav aria-label="스페이스 종류">{[['all', '전체', Library], ['documents', '페이지', FileText], ['images', '이미지', ImageIcon], ['other', '기타 파일', FolderOpen]].map(([id, label, Icon]) => { const NavIcon = Icon as typeof Library; return <button key={String(id)} className="spaces-nav" aria-current={filter === id && !preview ? 'page' : undefined} onClick={() => { setFilter(String(id)); onBack(); setSidebar(false); }}><NavIcon size={19} />{String(label)}</button>; })}</nav>
      <p className="spaces-section-label">생성된 파일</p><div className="spaces-recents">{files.slice(0, 8).map(file => <button className="spaces-nav" key={file.path} aria-current={preview?.path === file.path ? 'page' : undefined} onClick={() => { onFile(file.path); setSidebar(false); }}><FileIcon path={file.path} /><span>{file.path.split('/').pop()}</span></button>)}</div><p className="spaces-sidebar-note">대화에서 만든 문서와 자료가 여기에 모입니다.</p>
    </aside>
    <main className="spaces-main"><header className="spaces-topbar"><button className="icon-button spaces-menu" aria-label="파일 탐색 열기" aria-expanded={sidebar} onClick={() => setSidebar(!sidebar)}><PanelLeft size={19} /></button>{preview ? <button className="spaces-title-pill" onClick={onBack}><FileIcon path={preview.path} /><span>{preview.path.split('/').pop()}</span><ChevronDown size={16} /></button> : <strong>{filter === 'all' ? '전체' : filter === 'documents' ? '페이지' : filter === 'images' ? '이미지' : '기타 파일'}</strong>}<div className="spaces-topbar-actions">{preview && <><select aria-label="미리보기 배율" value={zoom} onChange={e => setZoom(e.target.value)}>{['75', '100', '125', '150'].map(value => <option key={value} value={value}>{value}%</option>)}</select><a className="icon-button" aria-label="파일 다운로드" href={fileUrl(preview.path, true)}><Download size={19} /></a></>}<button className="icon-button" aria-label="스페이스 닫기" onClick={onClose}><X size={19} /></button></div></header>
      {preview ? <div className="spaces-viewer"><div className="spaces-viewer-scroll">
        {preview.loading ? <div className="spaces-empty"><Loader2 className="spin" size={30} /><p>파일을 여는 중…</p></div> : preview.error ? <div className="spaces-empty" role="alert"><File size={40} /><p>{preview.error}</p><button className="button" onClick={() => onFile(preview.path)}>다시 시도</button></div> : kind(preview.path) === 'images' ? <img className="spaces-image" style={{ width: `${Number(zoom)}%` }} src={fileUrl(preview.path)} alt={preview.path.split('/').pop()} /> : /\.pdf$/i.test(preview.path) ? <iframe className="spaces-pdf" title={preview.path} src={fileUrl(preview.path) + '#zoom=' + zoom} /> : preview.text !== undefined ? <div className="spaces-readable" style={{ fontSize: `${Number(zoom)}%` }}>{/\.md$/i.test(preview.path) ? <article><Markdown>{preview.text}</Markdown></article> : <pre>{preview.text}</pre>}</div> : <div className="spaces-empty"><File size={44} /><h2>{preview.path.split('/').pop()}</h2><p>이 파일은 다운로드해서 열 수 있어요.</p><a className="button" href={fileUrl(preview.path, true)}><Download size={16} />파일 다운로드</a></div>}
        </div><form className="spaces-ask" onSubmit={e => { e.preventDefault(); ask(); }}><input aria-label="이 파일에 대한 질문" placeholder="이 파일에 대해 물어보세요" value={question} onChange={e => setQuestion(e.target.value)} /><button aria-label="질문을 채팅 초안에 넣기" disabled={!question.trim()}><ArrowUp size={19} /></button></form></div> : <div className="spaces-library-page">
        <div className="spaces-library-toolbar"><label className="settings-search"><Search size={18} /><input aria-label="파일 검색" placeholder="검색" value={query} onChange={e => setQuery(e.target.value)} /></label><button className="spaces-create" onClick={() => onCompose('새 문서 초안을 만들어줘')}>새로 만들기<SquarePen size={16} /></button></div>
        <div className="spaces-library-tabs"><span>{filter === 'all' ? '전체 항목' : filter === 'documents' ? '페이지' : filter === 'images' ? '이미지' : '기타 파일'} <small>{matches.length}</small></span><div><button className="icon-button" aria-label="격자로 보기" aria-pressed={grid} onClick={() => setGrid(true)}><Grid2X2 size={19} /></button><button className="icon-button" aria-label="목록으로 보기" aria-pressed={!grid} onClick={() => setGrid(false)}><List size={19} /></button></div></div>
        <section className="spaces-starters"><h3>시작하기</h3><div>{[['페이지 시작하기', '새 문서 초안을 만들어줘'], ['할 일 목록', '할 일 목록 문서를 만들어줘'], ['프로젝트 관리표', '프로젝트 관리표를 만들어줘'], ['주간 업데이트', '주간 업데이트 문서 초안을 만들어줘']].map(([label, prompt]) => <button key={label} onClick={() => onCompose(prompt)}><FileText size={22} /><span>{label}</span></button>)}</div></section>
        {matches.length ? <div className={grid ? 'spaces-artifacts as-grid' : 'spaces-artifacts'}>{!grid && <div className="spaces-table-head"><span>이름</span><span>소스</span><span>크기</span></div>}{matches.map(file => <button className="spaces-artifact" key={file.path} onClick={() => onFile(file.path)}><span className="spaces-artifact-name"><FileIcon path={file.path} /><span><strong>{file.path.split('/').pop()}</strong><small>{file.path}</small></span></span><span className="spaces-artifact-source">dot 컴퓨터</span><span className="spaces-artifact-size">{size(file.size)}</span></button>)}</div> : <div className="spaces-empty"><FolderOpen size={38} /><h2>{files.length ? '일치하는 파일이 없습니다' : '작업의 결과를 한곳에서'}</h2><p>{files.length ? '다른 검색어나 파일 종류를 선택해 보세요.' : '문서, 이미지, 자료를 만들면 여기에 표시됩니다.'}</p></div>}
      </div>}
      {selected && <span className="sr-only">{selected.path}, {size(selected.size)}</span>}
    </main>
  </section>;
}
